#!/usr/bin/env python3
"""Generates the Example module's panels (light and dark) and its custom knob and button graphics.

Everything is written to ../res. Each panel carries a hidden "components" layer in the SDK helper.py
convention (red params, green inputs, blue outputs, magenta lights, yellow custom widgets), and the C++
side reads it back at runtime to place every widget (see PanelLayout in src/ui.hpp). That makes this
file the single place the layout lives: move a control here, re-run, `make install`, and the artwork,
the widget and its screen readout all follow without touching C++.

Prefer drawing in Inkscape? Edit the generated SVGs directly and stop running this script; the
components layer works the same either way. Keep text as paths, since Rack's SVG renderer ignores <text>.

Needs fontTools:  python3 -m pip install fonttools
"""
import json
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = json.loads((ROOT / 'plugin.json').read_text())


def num(v):
    return f'{v:.3f}'.rstrip('0').rstrip('.')


def mix(a, b, t):
    """Blend two #RRGGBB colours."""
    pa, pb = bytes.fromhex(a[1:]), bytes.fromhex(b[1:])
    return '#' + bytes(round(x + (y - x) * t) for x, y in zip(pa, pb)).hex().upper()


class Font:
    def __init__(self, path):
        tt = TTFont(path)
        self.glyphs, self.cmap = tt.getGlyphSet(), tt.getBestCmap()
        self.upem = tt['head'].unitsPerEm
        self.cap = tt['OS/2'].sCapHeight / self.upem

    def width(self, text, size):
        return sum(self.glyphs[self.cmap[ord(c)]].width for c in text) * size / self.upem

    def path(self, text, x, y, size, anchor='middle'):
        """Outlines of `text` as SVG path data, with its cap height centred on `y`."""
        x -= {'start': 0, 'middle': 0.5, 'end': 1}[anchor] * self.width(text, size)
        y += self.cap * size / 2
        s = size / self.upem
        pen = SVGPathPen(self.glyphs, num)
        for c in text:
            glyph = self.glyphs[self.cmap[ord(c)]]
            glyph.draw(TransformPen(pen, (s, 0, 0, -s, x, y)))
            x += glyph.width * s
        return pen.getCommands()


NUNITO = Font(ROOT / 'res-src/fonts/Nunito-Bold.ttf')

# Colour roles, filled into the artwork per theme. Rack picks the dark panel when the user prefers dark panels.
THEMES = {
    '': dict(panel='#ECEBE8', ink='#3A3A3C', title='#2B2B2D', line='#C4C2BE', footer='#A9A8A4',
             bezel='#2F3032', glass='#030304', box='#2D2E31', box_ink='#E4E3E0'),
    '-dark': dict(panel='#2B2C2E', ink='#C9C8C4', title='#ECEBE8', line='#4A4B50', footer='#707175',
                  bezel='#141516', glass='#030304', box='#1C1D1F', box_ink='#C9C8C4'),
}
PASTELS = dict(yellow='#F4D394', green='#C4DDAB', teal='#A4D9D5', lavender='#B7C0F2',
               salmon='#F5B3A6', cyan='#ABE6F5', pink='#F7BDD6')
COMPONENT_COLORS = dict(PARAM='#FF0000', INPUT='#00FF00', OUTPUT='#0000FF', LIGHT='#FF00FF', WIDGET='#FFFF00')

HP = 5.08
KNOB_R, SOFT_R, BUTTON_R = 5.5, 3.75, 3.6  # radii (mm) of the components generated below
LABEL = 2.6  # label font size (mm)


def document(width, height, body):
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by res-src/panel.py -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" '
            f'width="{num(width)}mm" height="{num(height)}mm" viewBox="0 0 {num(width)} {num(height)}">\n{body}\n</svg>\n')


class Panel:
    """Artwork with {role} colour placeholders, plus the components layer that positions the widgets."""

    def __init__(self, width, height):
        self.width, self.height = width, height
        self.art, self.components = [], []

    def rect(self, x, y, w, h, r, fill):
        self.art.append(f'<rect x="{num(x)}" y="{num(y)}" width="{num(w)}" height="{num(h)}" rx="{num(r)}" fill="{{{fill}}}"/>')

    def line(self, x1, y1, x2, y2, stroke='line', width=0.35):
        self.art.append(f'<path d="M{num(x1)} {num(y1)}L{num(x2)} {num(y2)}" stroke="{{{stroke}}}" stroke-width="{num(width)}"/>')

    def text(self, s, x, y, size=LABEL, fill='ink', anchor='middle'):
        self.art.append(f'<path d="{NUNITO.path(s, x, y, size, anchor)}" fill="{{{fill}}}"/>')

    def place(self, name, x, y, w=0, h=0):
        """Marks where the widget for C++ enum `name` (FREQ_PARAM, OUT_LIGHT, SCREEN_WIDGET...) goes.
        The suffix picks the helper.py colour; a size makes it a rectangle instead of a centre point."""
        kind = name.rsplit('_', 1)[1]
        attrs = f'id="{name}" inkscape:label="{name[:-len(kind) - 1].lower()}" fill="{COMPONENT_COLORS[kind]}"'
        if w:
            self.components.append(f'<rect {attrs} x="{num(x)}" y="{num(y)}" width="{num(w)}" height="{num(h)}"/>')
        else:
            self.components.append(f'<circle {attrs} cx="{num(x)}" cy="{num(y)}" r="1"/>')

    def title(self, slug):
        """The module's name from plugin.json at the top, the brand at the bottom between the screws."""
        name = next(m['name'] for m in MANIFEST['modules'] if m['slug'] == slug)
        self.text(name.lower(), self.width / 2, 6.3, size=5.2, fill='title')
        self.text(MANIFEST['brand'], self.width / 2, self.height - 2.54, size=2.3, fill='footer')

    def svg(self, theme):
        art = '\n    '.join(self.art).format(**theme)
        components = '\n    '.join(self.components)
        return document(self.width, self.height,
                        f'  <g id="artwork" inkscape:groupmode="layer" inkscape:label="artwork">\n    {art}\n  </g>\n'
                        f'  <g id="components" inkscape:groupmode="layer" inkscape:label="components" style="display:none">\n'
                        f'    {components}\n  </g>')


def example():
    w, h = 22 * HP, 128.5
    sx, sy, sw, sh = 4.0, 11.0, 76.0, 40.0  # the screen; C++ draws its graphics and readouts inside
    bezel = 1.3
    columns = [sx + sw * (i + 0.5) / 4 for i in range(4)]
    right = w - 8.25

    p = Panel(w, h)
    p.rect(0, 0, w, h, 0, 'panel')
    p.title('Example')

    p.rect(sx - bezel, sy - bezel, sw + 2 * bezel, sh + 2 * bezel, 2.6, 'bezel')
    p.rect(sx, sy, sw, sh, 1.4, 'glass')
    p.place('SCREEN_WIDGET', sx, sy, sw, sh)

    # Soft keys: a line from the screen's edge to each knob, its value shown on screen where the line meets it.
    for name, y in zip(['RANGE', 'MODE', 'CYCLES', 'TRAIL'], [16.0, 24.5, 33.0, 41.5]):
        p.line(sx + sw + bezel, y, right, y)
        p.text(name, right - SOFT_R - 1.0, y - 2.0, anchor='end')
        p.place(f'{name}_PARAM', right, y)

    # Modulatable parameters, one per column: screen readout, label, knob, attenuverter, CV input.
    knob_y, atten_y, jack_y = 66.0, 78.5, 89.5
    for x, name in zip(columns, ['FREQ', 'SHAPE', 'SKEW', 'DRIVE']):
        p.line(x, sy + sh + bezel, x, knob_y - 10.4)
        p.line(x, knob_y, x, jack_y)
        p.text(name, x, knob_y - 8.5)
        p.place(f'{name}_PARAM', x, knob_y)
        p.place(f'{name}_CV_PARAM', x, atten_y)
        p.place(f'{name}_INPUT', x, jack_y)

    for name, label, y in [('VOCT', 'V/OCT', knob_y), ('SYNC', 'SYNC', jack_y)]:
        p.text(label, right, y - 8.5)
        p.place(f'{name}_INPUT', right, y)

    # Bottom row: a momentary button, a toggle switch, and the outputs in their dark box.
    label_y, y = 100.5, 110.0
    p.text('RESET', columns[0], label_y)
    p.place('RESET_PARAM', columns[0], y)
    p.text('POLARITY', columns[1], label_y)
    p.place('POLARITY_PARAM', columns[1] - 2.5, y)
    p.text('UNI', columns[1] + 0.8, y - 2.1, size=2.0, anchor='start')
    p.text('BI', columns[1] + 0.8, y + 2.1, size=2.0, anchor='start')

    bx, by = 44.0, 96.0
    bw, bh = right + 4.75 - bx, 24.5
    p.rect(bx, by, bw, bh, 2.0, 'box')
    for i, (name, light) in enumerate([('OUT', True), ('PHASE', False), ('EOC', True)]):
        x = bx + bw * (i + 0.5) / 3
        p.text(name, x, label_y, fill='box_ink')
        p.place(f'{name}_OUTPUT', x, y)
        if light:
            p.place(f'{name}_LIGHT', x + NUNITO.width(name, LABEL) / 2 + 2.2, label_y)
    return p


def knob_bg(r, cap):
    """Static part of a knob: dark skirt and coloured cap, lit from the top left. The cap's id lets the
    C++ side read its colour, so a knob's screen readout always matches the knob."""
    c = num(r)
    return document(2 * r, 2 * r, f'''  <defs>
    <linearGradient id="skirt" x1="0" y1="0" x2="0" y2="{num(2 * r)}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#4A4A50"/><stop offset="1" stop-color="#17171A"/>
    </linearGradient>
    <radialGradient id="shine" cx="{num(r * 0.8)}" cy="{num(r * 0.7)}" r="{num(r * 0.7)}" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#FFFFFF" stop-opacity="0.4"/><stop offset="1" stop-color="#FFFFFF" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <circle cx="{c}" cy="{c}" r="{c}" fill="url(#skirt)"/>
  <circle id="cap" cx="{c}" cy="{c}" r="{num(r * 0.8)}" fill="{cap}"/>
  <circle cx="{c}" cy="{c}" r="{num(r * 0.68)}" fill="{mix(cap, '#FFFFFF', 0.15)}"/>
  <circle cx="{c}" cy="{c}" r="{num(r * 0.68)}" fill="url(#shine)"/>''')


def knob_pointer(r, length, width):
    """Rotating part of a knob: just the pointer, so the lighting on the static part stays put."""
    c = num(r)
    return document(2 * r, 2 * r, f'  <path d="M{c} {num(r * (1 - length[0]))}V{num(r * (1 - length[1]))}" '
                                  f'stroke="#202023" stroke-width="{num(width)}" stroke-linecap="round"/>')


def button(r, fill):
    c = num(r)
    return document(2 * r, 2 * r, f'  <circle cx="{c}" cy="{c}" r="{num(r - 0.35)}" fill="{fill}" stroke="#141416" stroke-width="0.6"/>')


def write(path, text):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(path.relative_to(ROOT))


# Module slug -> function building its panel; each becomes res/<slug>.svg and res/<slug>-dark.svg.
PANELS = {
    'Example': example,
    # your panels here
}

if __name__ == '__main__':
    for slug, build in PANELS.items():
        panel = build()
        for suffix, theme in THEMES.items():
            write(ROOT / f'res/{slug}{suffix}.svg', panel.svg(theme))
    components = ROOT / 'res/components'
    for name, color in PASTELS.items():
        write(components / f'PastelKnob_bg-{name}.svg', knob_bg(KNOB_R, color))
    write(components / 'PastelKnob.svg', knob_pointer(KNOB_R, (0.25, 0.7), 0.8))
    write(components / 'SoftKnob_bg.svg', knob_bg(SOFT_R, '#E2E1DC'))
    write(components / 'SoftKnob.svg', knob_pointer(SOFT_R, (0.25, 0.72), 0.6))
    write(components / 'PushButton_0.svg', button(BUTTON_R, '#FAFAF7'))
    write(components / 'PushButton_1.svg', button(BUTTON_R, '#CFCEC9'))
